# Use a base image with JDK and Maven installed
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-alpine
COPY --from=build /app/target/fts.jar /app/fts.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/fts.jar"]
